# (APPENDIX) 付録 {.unnumbered}

# よく使うアラビア語湾岸方言の単語・フレーズ {#appendix_a}

湾岸方言と上に書いているが、標準語も混じっているので、あしからず。\
思いつきで書いているので、リストの順番に特に意味はない。

なお、発音については、[BGN/PCGNラテン文字表記法](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1119536/ROMANIZATION_OF_ARABIC_-_Nov_22.pdf)に従った。

参考にしたもの:

-   経験
-   Qatari Phrasebook
-   Conversational Arabic Quick and Easy (Qatari Dialect)
-   Complete Spoken Arabic

+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| アラビア語                      | 発音                       | 日本語                            | 備考（と言う名の思いつくままに書いたコメント）                                                                                                                                    |
+================================:+============================+===================================+===================================================================================================================================================================================+
| تَمام                            | tamām                      | Ok, 了解                          | 恐らく、持田がカタール派遣間で一番使った単語。ちなみにトルコ語でも同じ意味だからトルコ人にも通じる。                                                                              |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| شَخْبارَك （m.）<br>شـَخْبارَچ （f.） | shakhbārak<br>shakhbārach  | お元気ですか?                     | كيف حارك の代わりに使える。これを使うとカタール人に驚かれる。ちなみに女性形を使ったことは一度もなかった。あと、چは本来のアラビア語にはない音でchと発音する。ペルシャ語の影響かな? |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ... أبي                         | abbī ...                   | 私は...が欲しい（したい）         | お茶が欲しければأبي چاي、行きたい所があれば、<場所> أبي أروحと言った感じでかなり万能。動詞も未完了形を付けれる。お父さんではない。                                                |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| سِفَارة                           | sifārah                    | 大使館                            | こんなの使うわけないだろ～、と思うなかれ。意外と重要な単語。大使館に呼ばれるかもしれないからね（実際、派遣初日に呼ばれて焦った）。                                                |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| جَواز السَفَر                      | jawāz ssafar               | パスポート                        | ビザの更新が必要な時があるので覚えておこう。                                                                                                                                      |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| عَسْكَر<br>عسكري（adj）            | 'askar<br>'askarī          | 軍隊                              | 一般人はいらないが立場上必要になる単語。形容詞形では、軍人という意味もあるから自己紹介にも使える。<br>مُعَسْكَرで「駐屯地, 基地」                                                     |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| مُلْحَق العسكري                    | mulḩaq al-'skarī           | 駐在武官                          | クウェートの防衛駐在官（カタールと兼轄）がカタールに来ることもあるから、覚えといて損はない。                                                                                      |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| مُرَشَح الضَابِط                     | murashaḩ ḑḑābiţ            | 士官候補生                        | 単にمرشحでも通じる。                                                                                                                                                              |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| مُدَرِّب                            | mudarrib                   | 指導官, コーチ                    | ABMMCの下士官教官を指す。英語ではCoachで、人によってはteacherを使っている人もいる。                                                                                               |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| أنا مِسْتَعِد                       | anā mista'id               | 準備okです                        | よし行くぞー、というときに使おう                                                                                                                                                  |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| مُشكِلة                           | mushkilah                  | 問題                              | 問題は問題でもproblemの方。何か困ったときやダメなときは、これを使って助けを求めよう。それにしても発音が「虫けら」みたいで面白い。                                                 |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| في ...؟                         | fī ... ?                   | ～はありますか?                   | 湾岸方言の言い方。かなり単純化されててすごい楽。                                                                                                                                  |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| مافي                            | māfī                       | （ものなどが）ない                | これもかなり使う。 مافي مشكلة 「問題ない」など                                                                                                                                    |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| تَكْمِيل                           | takmīl                     | 点呼                              | このつづりが正しいか検証できてないので、正確なものかは分からない。点呼はあちらでもあるので注意!                                                                                   |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ساعة كم الحين؟                  | sā'ah kam al-ḩīn           | 今何時ですか?                     | 標準語だと疑問詞が最初に来るはずだが、湾岸方言だと逆となる。                                                                                                                      |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| الحِين                           | al-ḩīn                     | 今                                | 標準語はالأن                                                                                                                                                                      |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| فْلوس                            | flūs                       | お金                              | お金は大事。!!مافي فلوس                                                                                                                                                           |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| مَشْكور                           | mashkūr                    | ありがとう                        | شكراでいいかなと思いつつ、一応追加しておく。                                                                                                                                      |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| رُوح/ يِروح                       | rūḩ/ yirūḩ                 | 行く                              | 行きたい場所を伝えよう! أروح سيتي سنتر（シティーセンター[モールの名前]に行きます。）                                                                                              |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| وَين                             | wain                       | どこ（疑問詞）                    | 発音はどちらかというweinな気がする。أينの代わりに使える。                                                                                                                         |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| مَاي                             | māi                        | 水                                | 標準語のماءより発音が楽。カタールの水はとても安い（どうでもいい情報）。                                                                                                           |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ُما فَهَمت                         | mā fahamtu                 | わかりません                      | 自分が理解していないということを伝えるのって勇気いるよね。                                                                                                                        |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ماعرف                           | mā'araf                    | 知りません                        | 知らないことはどんどん聞こう!                                                                                                                                                     |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| أنا جَوْعان                       | anā jaw3ān                 | お腹空きました                    | カタール人は店で大量にモノを頼む。全部食べる必要はない(食べきるの無理)。                                                                                                          |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| سَلَّة قَمامة                       | sallah qamāmah             | ゴミ箱                            | カタールに分別なんて概念は存在しない。                                                                                                                                            |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| خَلاص                            | khalāş                     | 終わりました                      | 終わりのないものなどない。つまり必須の単語。                                                                                                                                      |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| مُتَقَّدِم                           | mutaqqadim                 | 3年生                             | 自分の学年は言える様にしておこう。!!يا متقدم                                                                                                                                      |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| خَريج                            | kharīj                     | 4年生                             | 4年生らしいが辞書だと「卒業生」という意味。多分通じるはず...                                                                                                                      |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| مُسْتَجِد                           | mustajid                   | 1年生                             | 原義は「新人」                                                                                                                                                                    |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| مُتَوَسِّط                           | mutawassiţ                 | 2年生                             | 原義は「中間, 平均」                                                                                                                                                              |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| كيس                             | kīs                        | 袋                                | ゴミ袋とかレジ袋とか、そういった類のもの。欲しい時あるでしょう?                                                                                                                   |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| الخَليج                          | al-Khalīj                  | 湾岸                              | 日本人はペルシャ湾というが、カタールでは「アラビア湾, خليج العربي」という。まぁ、そう呼ぶよなぁ。                                                                                 |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ... مُمْكِن                        | mumkin ...                 | ... できますか?                   | ...の部分には未完了動詞や名詞が入る。                                                                                                                                             |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| أَخْتاج                           | 'akhtāj                    | 私は～が必要です                  | 「欲しい」よりも強い感じだよね。                                                                                                                                                  |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| شو اسمك؟<br>شو اسمچ؟            | shi-smak<br>shi-smach      | あなたの名前は何ですか?           | شوの発音が文字通りではないので注意。شِنو「何」を省略したものと思われる。<br>女性形は使っ(ry                                                                                        |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| مُكِيف                            | mukīf                      | エアコン                          | カタールの空調は強烈に寒いので半袖短パンはやめといた方がいい。<br>寒い時は、سَكَّرْ مكيف「空調を切って」と言おう。                                                                    |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| دَقِيقة                           | daqīqah / dagīgah          | ちょっと待ってください            | 原義は「分」。<br>湾岸方言だとقはgの音になる。まぁ、そっちの方が楽だよね。                                                                                                        |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| أَكِيد                            | akīd                       | もちろん                          | of couseのような使い方ができる。                                                                                                                                                  |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| إشلون تِقول هاي بالعربي؟         | shlūn tigūl hāy bil-'arabī | これはアラビア語で何と言いますか? | هذا = هاي<br>كيف = اشلون<br>                                                                                                                                                      |
|                                 |                            |                                   |                                                                                                                                                                                   |
|                                 |                            |                                   | だから標準語だとكيف تَقول هاذا بالعربية؟となる(はず)                                                                                                                               |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| شَنْطة                            | shanţah                    | かばん                            | 同じ意味のحقيبةより聞いた単語。トルコ語もçantaだから、ペルシャ語が語源じゃないかな。                                                                                              |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| أَيْو                             | aywa                       | はい                              | نعمの代わりに使えるYesの表現。                                                                                                                                                    |
+---------------------------------+----------------------------+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
